USE `husky-buddy-orig`;

INSERT INTO husky_user (first_name, last_name, email, year, verification_status) 
VALUES
  ('Aiden', 'Chen', 'che.aid@northeastern.edu', '2nd', 'verified'),
  ('Sophia', 'Patel', 'pat.sop@northeastern.edu', '3rd', 'unverified'),
  ('Liam', 'Rivera', 'riv.lia@northeastern.edu', '4th', 'verified'),
  ('Emma', 'Johnson', 'joh.emm@northeastern.edu', '5th', 'pending'),
  ('Noah', 'Kim', 'kim.noa@northeastern.edu', 'Grad', 'verified'),
  ('Olivia', 'Nguyen', 'ngu.oli@northeastern.edu', '1st', 'verified'),
  ('Lucas', 'Martinez', 'mar.luc@northeastern.edu', '2nd', 'verified'),
  ('Ava', 'Lee', 'lee.ava@northeastern.edu', '3rd', 'verified'),
  ('Mason', 'Kowalski', 'kow.mas@northeastern.edu', '4th', 'verified'),
  ('Isabella', 'Osei', 'ose.isa@northeastern.edu', '5th', 'verified'),
  ('Ethan', 'Murphy', 'mur.eth@northeastern.edu', 'Grad', 'verified'),
  ('Mia', 'Hassan', 'has.mia@northeastern.edu', '1st', 'verified'),
  ('Logan', 'Tanaka', 'tan.log@northeastern.edu', '2nd', 'verified'),
  ('Charlotte', 'Williams', 'wil.cha@northeastern.edu', '3rd', 'verified'),
  ('Jackson', 'Santos', 'san.jac@northeastern.edu', '4th', 'verified'),
  ('Amelia', 'Gupta', 'gup.ame@northeastern.edu', '5th', 'verified'),
  ('Amir', 'Bakr', 'bak.ami@northeastern.edu', 'Grad', 'pending'),
  ('Zoe', 'Thompson', 'tho.zoe@northeastern.edu', '1st', 'verified'),
  ('Carlos', 'Diaz', 'dia.car@northeastern.edu', '2nd', 'verified'),
  ('Chloe', 'Park', 'par.chl@northeastern.edu', '3rd', 'verified'),
  ('Mateo', 'Reyes', 'rey.mat@northeastern.edu', '4th', 'verified'),
  ('Riley', 'Singh', 'sin.ril@northeastern.edu', '5th', 'verified'),
  ('Owen', 'Moore', 'moo.owe@northeastern.edu', 'Grad', 'verified'),
  ('Layla', 'Walsh', 'wal.lay@northeastern.edu', '1st', 'pending'),
  ('Nolan', 'Okonkwo', 'oko.nol@northeastern.edu', '2nd', 'verified'),
  ('Penelope', 'Yamamoto', 'yam.pen@northeastern.edu', '3rd', 'verified'),
  ('Dylan', 'Fernandez', 'fer.dyl@northeastern.edu', '4th', 'verified'),
  ('Aria', 'Ahmed', 'ahm.ari@northeastern.edu', '5th', 'verified'),
  ('Ryan', 'Brown', 'bro.rya@northeastern.edu', 'Grad', 'verified'),
  ('Nora', 'Davis', 'dav.nor@northeastern.edu', '1st', 'verified'),
  ('Miles', 'Garcia', 'gar.mil@northeastern.edu', '2nd', 'verified'),
  ('Luna', 'Wilson', 'wil.lun@northeastern.edu', '3rd', 'verified'),
  ('Caleb', 'Anderson', 'and.cal@northeastern.edu', '4th', 'verified'),
  ('Lily', 'Thomas', 'tho.lil@northeastern.edu', '5th', 'verified'),
  ('Isaac', 'Jackson', 'jac.isa@northeastern.edu', 'Grad', 'verified'),
  ('Scarlett', 'White', 'whi.sca@northeastern.edu', '1st', 'verified'),
  ('Adrian', 'Harris', 'har.adr@northeastern.edu', '2nd', 'verified'),
  ('Hannah', 'Martin', 'mar.han@northeastern.edu', '3rd', 'verified'),
  ('Eli', 'Taylor', 'tay.eli@northeastern.edu', '4th', 'unverified'),
  ('Stella', 'Lewis', 'lew.ste@northeastern.edu', '5th', 'verified');

INSERT INTO campus_spot (spot_name, location) VALUES
  ('Curry Student Center','346 Huntington Ave'),
  ('Centennial Common','Northeastern University'),
  ('The Fenway','Northeastern University'),
  ('Shillman Hall','115 Forsyth St'),
  ('Ryder Hall','50 Leon St'),
  ('International Village Dining','840 Columbus Ave'),
  ('Stetson East Dining','219 St Botolph St'),
  ('West Village F Café','440 Huntington Ave'),
  ('Ells Hall','40 Leon St'),
  ('Churchill Hall','51 Forsyth St'),
  ('Behrakis Health Sciences Center','360 Huntington Ave'),
  ('ISEC Building','805 Columbus Ave'),
  ('Columbus Place','305 Columbus Ave'),
  ('Boston Public Library','700 Boylston St'),
  ('Copley Square','Copley Square'),
  ('Back Bay Station','145 Dartmouth St'),
  ('Fenway Park Area','4 Yawkey Way'),
  ('The Verb Hotel Patio','1271 Boylston St'),
  ('Mission Hill Coffee','1469 Tremont St'),
  ('JP Licks Fenway','1618 Tremont St'),
  ('Whole Foods Fenway','181 Cambridge St'),
  ('Flour Bakery','1595 Washington St'),
  ('Tremont Street Green','Tremont St'),
  ('Starbucks on Huntington','368 Huntington Ave'),
  ('Pho Basil','177 Massachusetts Ave'),
  ('University Health & Counseling','360 Huntington Ave'),
  ('Dodge Hall','101 Leon St'),
  ('Kariotis Hall','360 Huntington Ave'),
  ('East Village Café','East Village'),
  ('Alumni Pavilion','Northeastern University');

-- ===== icebreaker_prompt (35 rows) =====
INSERT INTO icebreaker_prompt (prompt_text, category) VALUES
  ('What is your favorite place to study on campus?', 'Campus Life'),
  ('What club, sport, or activity have you enjoyed the most at Northeastern?', 'Student Life'),
  ('If you could grab food anywhere near campus right now, where would you go?', 'Food'),
  ('What is your favorite co-op story or dream co-op placement?', 'Careers'),
  ('What is one class that surprised you in a good way?', 'Academics'),
  ('What is your go-to late-night snack or study fuel?', 'Food'),
  ('What is the most underrated spot on or near campus?', 'Campus Life'),
  ('If you could add one major to Northeastern, what would it be?', 'Academics'),
  ('What is your best memory from Fenway?', 'Campus Life'),
  ('What is something about Boston you wish you had known sooner?', 'Campus Life'),
  ('What is your favorite student org on campus and why?', 'Student Life'),
  ('What is the most interesting thing you have learned this semester?', 'Academics'),
  ('If Northeastern had an unofficial motto, what would it be?', 'Campus Life'),
  ('What is one book, show, or podcast you have recommended to everyone?', 'Entertainment'),
  ('What skill do you want to learn before you graduate?', 'Personal Growth'),
  ('What is your ideal Saturday in Boston?', 'Lifestyle'),
  ('What is a co-op tip you wish someone had given you earlier?', 'Careers'),
  ('What is your favorite gym or fitness routine near campus?', 'Wellness'),
  ('Who is a professor at Northeastern who changed how you think?', 'Academics'),
  ('What is your go-to coffee order and where do you get it?', 'Food'),
  ('If you could live in any Boston neighborhood, which would you pick?', 'Lifestyle'),
  ('What is one thing you do to reset when you feel stressed?', 'Wellness'),
  ('What is your weirdest or funniest co-op moment?', 'Careers'),
  ('What is the best event you have attended at Northeastern?', 'Student Life'),
  ('What is one travel destination you have visited from Boston?', 'Lifestyle'),
  ('What is a Northeastern tradition you love?', 'Campus Life'),
  ('What is something on your bucket list before you graduate?', 'Personal Growth'),
  ('What is the best food spot you have discovered in the Fenway area?', 'Food'),
  ('What tech tool or app has changed how you study?', 'Academics'),
  ('What is your favorite way to explore Boston on a budget?', 'Lifestyle'),
  ('What is an internship or research project you are proud of?', 'Careers'),
  ('What is a cause or issue you care deeply about?', 'Personal Growth'),
  ('What is the best view you have found anywhere near campus?', 'Campus Life'),
  ('What would your Northeastern highlight reel include?', 'Student Life'),
  ('What is your most unpopular academic opinion?', 'Academics');

INSERT INTO admin (name, email, role) VALUES
  ('Marcus Webb','webb.ma@northeastern.edu','Community Manager'),
  ('Priya Shah','shah.pr@northeastern.edu','Moderation Lead'),
  ('Diane Torres','torres.di@northeastern.edu','Product Manager');